version: '3.8'

services:

  db:
    build:
      context: ./
      dockerfile: pg.Dockerfile
    image: db
    restart: unless-stopped
    container_name: psql-etl
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: root
    ports:
      - 5432:5432
    networks:
      - etl-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  etl-net:
    name: etl-net

volumes:
  pgdata:
    name: pgdata
