version: '3.8'

services:

  jp:
    build:
      context: ./
      dockerfile: jp32.Dockerfile
    image: jp
    restart: unless-stopped
    container_name: jp-etl
    depends_on:
      - db 
    ports:
      - 8888:8888
    networks:
      - etl-net
    entrypoint:
      jupyter lab --ip='0.0.0.0' --no-browser --allow-root --ServerApp.token='' --ServerApp.password='' #--IdentityProvider.token='' --PasswordIdentityProvider.hashed_password=''
    volumes:
      - jpdata:/jp
    #  - srcdata:/src
    env_file:
      - ./variables.env
  db:
    build:
      context: ./
      dockerfile: pg.Dockerfile
    image: db
    restart: unless-stopped
    container_name: psql-etl
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: root
    ports:
      - 5432:5432
    networks:
      - etl-net
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  etl-net:
    name: etl-net
volumes:
  jpdata:
    name: jpdata
  pgdata:
    name: pgdata
  #srcdata:
  #  name: srcdata
#include:
#  - docker-compose.yml
